import { type Metadata } from "next";

import { Urbanist } from "next/font/google";
import "../globals.css";
import SessionWrapper from "@/components/Auth/SessionWrapper";
import ReactQueryContext from "@/lib/ReactQueryContext";
import Navbar from "@/components/Navabr";
import { CityFilterProvider } from "@/contexts/city-filter-context";
import { FavoritesProvider } from "@/contexts/favorites-context";
import { RedeemProvider } from "@/contexts/redeem-context";
import { Toaster } from "sonner";
import Sidebar from "@/components/Sidebar";
import DashboardLayout from "@/components/DashboardLayout";

const urbanist = Urbanist({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-urbanist",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div lang="en" className="flex w-full">
      <DashboardLayout>{children}</DashboardLayout>
    </div>
  );
}
